# Generated by Django 5.2.17 on 2026-09-24 15:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0003_backfill_customer_codes'),
        ('organizations', '0002_quote_numbering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='رقم العرض')),
                ('revision', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('finalized', 'صادر'), ('sent', 'اتبعت'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('superseded', 'اتعدّل')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('issue_date', models.DateField(verbose_name='التاريخ')),
                ('valid_until', models.DateField(verbose_name='سريان العرض حتى')),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('prices_include_vat', models.BooleanField(default=False)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5)),
                ('intro_text', models.TextField(blank=True, verbose_name='النص الافتتاحي')),
                ('price_note', models.CharField(blank=True, max_length=300, verbose_name='ملحوظة الأسعار')),
                ('terms', models.JSONField(blank=True, default=list, verbose_name='الشروط')),
                ('internal_notes', models.TextField(blank=True, help_text='مش بتظهر للعميل', verbose_name='ملاحظات داخلية')),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('customer_snapshot', models.JSONField(blank=True, default=dict)),
                ('contact_snapshot', models.JSONField(blank=True, default=dict)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.contact', verbose_name='المسؤول')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer', verbose_name='العميل')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('parent_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='quotations.quotation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=150)),
                ('section_order', models.BigIntegerField(default=0, help_text='group order * 10000 + category order')),
                ('item_order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=250, verbose_name='الصنف')),
                ('unit_name', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['section_order', 'item_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=60)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['organization', 'status', '-issue_date'], name='quote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['organization', 'customer'], name='quote_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number', 'revision'), name='uniq_quote_number'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('quotation', 'product'), name='uniq_product_per_quote'),
        ),
        migrations.AddConstraint(
            model_name='quotesequence',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uniq_quote_sequence'),
        ),
    ]
