# Generated by Django 5.2.17 on 2026-09-26 08:32

import apps.quotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.quotations.models.pdf_upload_to),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
