# Generated by Django 5.2.17 on 2026-09-24 13:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=200)),
                ('kind', models.CharField(choices=[('group', 'مجموعة / شركة أم'), ('chain', 'سلسلة فنادق'), ('hotel', 'فندق'), ('resort', 'منتجع'), ('restaurant', 'مطعم / كافيه'), ('company', 'شركة'), ('other', 'أخرى')], default='hotel', max_length=20, verbose_name='النوع')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='مثلًا: الفندق تابع لسلسلة، والسلسلة تابعة لمجموعة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='customers.customer', verbose_name='تابع لـ')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='المنصب')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='الإدارة')),
                ('salutation', models.CharField(blank=True, help_text='مثلًا: أ. / م. / د.', max_length=20, verbose_name='اللقب')),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('email', 'إيميل'), ('both', 'الاتنين')], default='whatsapp', max_length=10, verbose_name='طريقة الإرسال المفضلة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='المسؤول الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'مسؤول',
                'verbose_name_plural': 'المسؤولين',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='المنصب')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='الإدارة')),
                ('salutation', models.CharField(blank=True, help_text='مثلًا: أ. / م. / د.', max_length=20, verbose_name='اللقب')),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('email', 'إيميل'), ('both', 'الاتنين')], default='whatsapp', max_length=10, verbose_name='طريقة الإرسال المفضلة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='المسؤول الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical مسؤول',
                'verbose_name_plural': 'historical المسؤولين',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContactChannel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('whatsapp', 'واتساب'), ('phone', 'تليفون'), ('email', 'إيميل')], max_length=10, verbose_name='النوع')),
                ('value', models.CharField(max_length=254, verbose_name='القيمة')),
                ('label', models.CharField(blank=True, help_text='مثلًا: شخصي / الشغل', max_length=50, verbose_name='وصف')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='اتبعتله قبل كده بنجاح')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical وسيلة تواصل',
                'verbose_name_plural': 'historical وسائل التواصل',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=200)),
                ('kind', models.CharField(choices=[('group', 'مجموعة / شركة أم'), ('chain', 'سلسلة فنادق'), ('hotel', 'فندق'), ('resort', 'منتجع'), ('restaurant', 'مطعم / كافيه'), ('company', 'شركة'), ('other', 'أخرى')], default='hotel', max_length=20, verbose_name='النوع')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='مثلًا: الفندق تابع لسلسلة، والسلسلة تابعة لمجموعة.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='تابع لـ')),
            ],
            options={
                'verbose_name': 'historical عميل',
                'verbose_name_plural': 'historical العملاء',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('whatsapp', 'واتساب'), ('phone', 'تليفون'), ('email', 'إيميل')], max_length=10, verbose_name='النوع')),
                ('value', models.CharField(max_length=254, verbose_name='القيمة')),
                ('label', models.CharField(blank=True, help_text='مثلًا: شخصي / الشغل', max_length=50, verbose_name='وصف')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='اتبعتله قبل كده بنجاح')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='customers.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'وسيلة تواصل',
                'verbose_name_plural': 'وسائل التواصل',
                'ordering': ['type', '-is_primary', 'id'],
                'constraints': [models.UniqueConstraint(fields=('contact', 'type', 'value'), name='uniq_contact_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'parent'), name='uniq_customer_name_in_parent', nulls_distinct=False),
        ),
    ]
