# Generated by Django 5.2.17 on 2026-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, help_text='حرفين أو أكتر بالإنجليزي، بيتكتبوا في رقم العرض: RG-2026/09/24', max_length=5, verbose_name='كود العميل'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='code',
            field=models.CharField(blank=True, help_text='حرفين أو أكتر بالإنجليزي، بيتكتبوا في رقم العرض: RG-2026/09/24', max_length=5, verbose_name='كود العميل'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='uniq_customer_code'),
        ),
    ]
