# Generated by Django 5.2.17 on 2026-09-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_backfill_customer_codes'),
        ('organizations', '0002_quote_numbering'),
        ('quotations', '0002_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'إيميل'), ('whatsapp', 'واتساب')], max_length=20)),
                ('recipient', models.CharField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'في الطابور'), ('sending', 'بيتبعت'), ('sent', 'اتبعت'), ('delivered', 'اتسلّم'), ('read', 'اتقرا'), ('failed', 'فشل')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=250)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('review_confirmed', models.BooleanField(default=False)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('contact_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.contactchannel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='quotations.quotation')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إرسال',
                'verbose_name_plural': 'عمليات الإرسال',
                'ordering': ['-queued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quotations.quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quotation', 'user'), name='uniq_review_per_user')],
            },
        ),
        migrations.CreateModel(
            name='SendingChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'إيميل'), ('whatsapp', 'واتساب')], max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعّل')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المرسل')),
                ('config_encrypted', models.TextField(blank=True)),
                ('sender_identity', models.CharField(blank=True, max_length=254, verbose_name='المرسل')),
                ('status', models.CharField(choices=[('unknown', 'لسه متجربش'), ('connected', 'شغال'), ('disconnected', 'مفصول'), ('needs_qr', 'محتاج QR'), ('error', 'فيه مشكلة')], default='unknown', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'قناة إرسال',
                'verbose_name_plural': 'قنوات الإرسال',
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='uniq_channel_kind')],
            },
        ),
    ]
