# Generated by Django 5.2.17 on 2026-10-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_whatsappnumber'),
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='scheduled_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.scheduledmessage'),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='whatsappnumber',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_wa_number'),
        ),
    ]
