# Generated by Django 5.2.17 on 2026-10-04 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'كاش'), ('card', 'فيزا'), ('instapay', 'InstaPay'), ('wallet', 'محفظة')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('is_refund', models.BooleanField(default=False, verbose_name='استرداد')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='scheduling.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['received_at', 'id'],
                'indexes': [models.Index(fields=['organization', 'received_at'], name='billing_pay_organiz_ebb53a_idx')],
            },
        ),
    ]
