# Generated by Django 5.2.17 on 2026-10-04 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_drug_specialty_and_more'),
        ('organizations', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'تصنيف أدوية',
                'verbose_name_plural': 'تصنيفات الأدوية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('common', 'Common'), ('occasional', 'Occasional'), ('not_typical', 'Not typical')], default='primary', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_categories', to='doctors.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_entries', to='prescriptions.drugcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='drugs', to='prescriptions.drugcategory', verbose_name='التصنيفات'),
        ),
        migrations.AddConstraint(
            model_name='drugcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_drug_category_name'),
        ),
        migrations.AddConstraint(
            model_name='doctorcategory',
            constraint=models.UniqueConstraint(fields=('doctor', 'category'), name='uniq_doctor_category'),
        ),
    ]
