# Generated by Django 5.2.17 on 2026-10-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_drugcategory_doctorcategory_drug_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150, verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='drug',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='الاسم العلمي'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='الاسم التجاري'),
        ),
    ]
