# Generated by Django 5.2.17 on 2026-10-04 17:41

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVisit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, verbose_name='الشكوى')),
                ('history', models.TextField(blank=True, verbose_name='التاريخ المرضي')),
                ('examination', models.TextField(blank=True, verbose_name='الفحص')),
                ('diagnosis', models.TextField(blank=True, verbose_name='التشخيص')),
                ('diagnosis_tags', models.JSONField(blank=True, default=list)),
                ('plan', models.TextField(blank=True, verbose_name='الخطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('followup_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='إعادة بعد (يوم)')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('finished', 'خلصت')], default='open', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appointment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduling.appointment')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='doctors.doctor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historical زيارة',
                'verbose_name_plural': 'historical الزيارات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, verbose_name='الشكوى')),
                ('history', models.TextField(blank=True, verbose_name='التاريخ المرضي')),
                ('examination', models.TextField(blank=True, verbose_name='الفحص')),
                ('diagnosis', models.TextField(blank=True, verbose_name='التشخيص')),
                ('diagnosis_tags', models.JSONField(blank=True, default=list)),
                ('plan', models.TextField(blank=True, verbose_name='الخطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('followup_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='إعادة بعد (يوم)')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('finished', 'خلصت')], default='open', max_length=10)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='scheduling.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='doctors.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVitals',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الطول (سم)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الضغط (الانقباضي)')),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الضغط (الانبساطي)')),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='النبض')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='الحرارة')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسبة الأكسجين %')),
                ('blood_glucose', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='السكر')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'historical علامات حيوية',
                'verbose_name_plural': 'historical العلامات الحيوية',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الطول (سم)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الضغط (الانقباضي)')),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الضغط (الانبساطي)')),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='النبض')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='الحرارة')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسبة الأكسجين %')),
                ('blood_glucose', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='السكر')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'علامات حيوية',
                'verbose_name_plural': 'العلامات الحيوية',
            },
        ),
    ]
