# Generated by Django 5.2.17 on 2026-10-04 18:02

import apps.clinical.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisit',
            name='followup_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='followup_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.clinical.models.attachment_path)),
                ('content_type', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('lab', 'تحليل'), ('radiology', 'أشعة'), ('report', 'تقرير'), ('other', 'أخرى')], default='other', max_length=10, verbose_name='النوع')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='العنوان')),
                ('taken_on', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-taken_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttachment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('file', models.TextField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('lab', 'تحليل'), ('radiology', 'أشعة'), ('report', 'تقرير'), ('other', 'أخرى')], default='other', max_length=10, verbose_name='النوع')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='العنوان')),
                ('taken_on', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('is_archived', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.visit')),
            ],
            options={
                'verbose_name': 'historical مرفق',
                'verbose_name_plural': 'historical المرفقات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
