# Generated by Django 5.2.17 on 2026-10-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('period_key', models.CharField(blank=True, max_length=20)),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'محجوز'), ('confirmed', 'مؤكد'), ('arrived', 'وصل'), ('in_consultation', 'جوه الكشف'), ('completed', 'خلص'), ('no_show', 'لم يحضر'), ('cancelled', 'ملغي'), ('rescheduled', 'اتأجل')], default='booked', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('phone', 'تليفون'), ('walk_in', 'حضور مباشر'), ('auto_rebook', 'إعادة حجز تلقائي'), ('whatsapp', 'واتساب'), ('online', 'أونلاين')], default='phone', max_length=20)),
                ('is_overbooked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('auto_rebooked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.appointment')),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('followup_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('rescheduled_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.appointment')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.visittype')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduling.appointment')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='DayLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('queue_numbers', models.JSONField(blank=True, default=dict)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_ledgers', to='doctors.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'doctor', 'date'], name='scheduling__organiz_a8826f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'patient', '-start_at'], name='scheduling__organiz_5f5cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'status', 'start_at'], name='scheduling__organiz_15aec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status__in', ['cancelled', 'rescheduled']), _negated=True), ('queue_number__isnull', False)), fields=('doctor', 'date', 'period_key', 'queue_number'), name='uniq_queue_number_per_period'),
        ),
        migrations.AddConstraint(
            model_name='dayledger',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='uniq_day_ledger'),
        ),
    ]
