# Generated by Django 5.2.17 on 2026-10-04 14:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_number', models.PositiveIntegerField(verbose_name='رقم الملف')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('dob_is_estimated', models.BooleanField(default=False, verbose_name='السن تقريبي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='الإيميل')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='اسم ولي الأمر')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='المهنة')),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('email', 'إيميل'), ('none', 'من غير رسايل')], default='whatsapp', max_length=10, verbose_name='القناة المفضلة')),
                ('messaging_consent', models.BooleanField(default=False, verbose_name='موافق على استقبال رسايل')),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إدارية')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('no_show_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='patients.patient')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('file_number', models.PositiveIntegerField(verbose_name='رقم الملف')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_normalized', models.CharField(db_index=True, editable=False, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('dob_is_estimated', models.BooleanField(default=False, verbose_name='السن تقريبي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='الإيميل')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='اسم ولي الأمر')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='المهنة')),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('email', 'إيميل'), ('none', 'من غير رسايل')], default='whatsapp', max_length=10, verbose_name='القناة المفضلة')),
                ('messaging_consent', models.BooleanField(default=False, verbose_name='موافق على استقبال رسايل')),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إدارية')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('no_show_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('merged_into', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historical مريض',
                'verbose_name_plural': 'historical المرضى',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='المرض المزمن')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'مرض مزمن',
                'verbose_name_plural': 'الأمراض المزمنة',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='الحساسية')),
                ('severity', models.CharField(choices=[('mild', 'خفيفة'), ('moderate', 'متوسطة'), ('severe', 'شديدة')], default='moderate', max_length=10, verbose_name='الشدة')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'verbose_name': 'حساسية',
                'verbose_name_plural': 'الحساسيات',
            },
        ),
        migrations.CreateModel(
            name='PatientFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(verbose_name='المفتاح')),
                ('label_ar', models.CharField(max_length=100, verbose_name='التسمية')),
                ('type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('choice', 'اختيار'), ('bool', 'صح/غلط')], default='text', max_length=10, verbose_name='النوع')),
                ('choices', models.JSONField(blank=True, default=list)),
                ('scope', models.CharField(choices=[('patient', 'المريض'), ('visit', 'الزيارة')], default='patient', max_length=10, verbose_name='النطاق')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'حقل إضافي',
                'verbose_name_plural': 'الحقول الإضافية',
                'ordering': ['scope', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatientSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'phone'], name='patients_pa_organiz_62612b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'name_normalized'], name='patients_pa_organiz_3d9581_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organization', 'file_number'), name='uniq_patient_file_number'),
        ),
        migrations.AddConstraint(
            model_name='patientfielddefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uniq_field_key_per_org'),
        ),
        migrations.AddConstraint(
            model_name='patientsequence',
            constraint=models.UniqueConstraint(fields=('organization',), name='uniq_patient_sequence_per_org'),
        ),
    ]
