# Generated by Django 5.2.17 on 2026-10-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='drug_specialty',
            field=models.CharField(blank=True, max_length=40, verbose_name='تخصص تصنيفات الأدوية'),
        ),
        migrations.AddField(
            model_name='historicaldoctor',
            name='drug_specialty',
            field=models.CharField(blank=True, max_length=40, verbose_name='تخصص تصنيفات الأدوية'),
        ),
    ]
