# Generated by Django 5.2.17 on 2026-09-24 11:04

import apps.organizations.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزي')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'منظمة',
                'verbose_name_plural': 'المنظمات',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, upload_to=apps.organizations.models.logo_upload_to, verbose_name='اللوجو')),
                ('primary_color', models.CharField(default='#AE171C', max_length=7, verbose_name='اللون الأساسي')),
                ('dark_color', models.CharField(default='#111111', max_length=7, verbose_name='اللون الغامق')),
                ('neutral_color', models.CharField(default='#F5F2EF', max_length=7, verbose_name='اللون المحايد')),
                ('section_row_color', models.CharField(default='#FBECEC', max_length=7, verbose_name='لون صف القسم')),
                ('tagline_ar', models.CharField(blank=True, max_length=300, verbose_name='السطر التعريفي')),
                ('phones', models.JSONField(blank=True, default=list, verbose_name='أرقام التليفون')),
                ('email_display', models.EmailField(blank=True, max_length=254, verbose_name='الإيميل الظاهر')),
                ('address_ar', models.CharField(blank=True, max_length=300, verbose_name='العنوان بالعربي')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='العنوان بالإنجليزي')),
                ('quote_number_prefix', models.CharField(default='AB', max_length=10, verbose_name='بادئة رقم العرض')),
                ('quote_number_format', models.CharField(default='{prefix}-{year}/{month:02d}-{seq:02d}', max_length=80, verbose_name='صيغة رقم العرض')),
                ('default_validity_days', models.PositiveSmallIntegerField(default=30, verbose_name='مدة سريان العرض (أيام)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('prices_include_vat', models.BooleanField(default=False, verbose_name='الأسعار شاملة الضريبة')),
                ('default_intro_text', models.TextField(blank=True, verbose_name='النص الافتتاحي')),
                ('price_note', models.CharField(blank=True, max_length=300, verbose_name='ملحوظة الأسعار')),
                ('default_terms', models.JSONField(blank=True, default=list, verbose_name='الشروط الافتراضية')),
                ('default_whatsapp_message', models.TextField(blank=True, verbose_name='رسالة WhatsApp الافتراضية')),
                ('default_email_subject', models.CharField(blank=True, max_length=200, verbose_name='عنوان الإيميل الافتراضي')),
                ('default_email_body', models.TextField(blank=True, verbose_name='نص الإيميل الافتراضي')),
                ('whatsapp_sender', models.CharField(blank=True, max_length=20, verbose_name='رقم WhatsApp للإرسال')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'إعدادات المنظمة',
                'verbose_name_plural': 'إعدادات المنظمات',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'مالك'), ('admin', 'مدير النظام'), ('manager', 'مدير'), ('sales', 'مبيعات'), ('viewer', 'مشاهد')], default='sales', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership')],
            },
        ),
    ]
