# Generated by Django 5.2.17 on 2026-10-04 13:54

import apps.organizations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزي')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'منظمة',
                'verbose_name_plural': 'المنظمات',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic_name_ar', models.CharField(blank=True, max_length=200, verbose_name='اسم العيادة بالعربي')),
                ('clinic_name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم العيادة بالإنجليزي')),
                ('logo', models.ImageField(blank=True, upload_to=apps.organizations.models.logo_upload_to, verbose_name='اللوجو')),
                ('primary_color', models.CharField(default='#AE171C', max_length=7, verbose_name='اللون الأساسي')),
                ('dark_color', models.CharField(default='#111111', max_length=7, verbose_name='اللون الغامق')),
                ('neutral_color', models.CharField(default='#F5F2EF', max_length=7, verbose_name='اللون المحايد')),
                ('phones', models.JSONField(blank=True, default=list, verbose_name='أرقام التليفون')),
                ('address_ar', models.CharField(blank=True, max_length=300, verbose_name='العنوان بالعربي')),
                ('map_link', models.URLField(blank=True, verbose_name='لينك الموقع على الخريطة')),
                ('working_hours_text', models.CharField(blank=True, max_length=300, verbose_name='مواعيد العمل (سطر الفوتر)')),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50, verbose_name='التوقيت')),
                ('whatsapp_sender', models.CharField(blank=True, max_length=20, verbose_name='رقم WhatsApp للإرسال')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'إعدادات المنظمة',
                'verbose_name_plural': 'إعدادات المنظمات',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'مالك'), ('admin', 'مدير النظام'), ('doctor', 'دكتور'), ('reception', 'استقبال'), ('viewer', 'مشاهد')], default='reception', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership')],
            },
        ),
    ]
