# Generated by Django 5.2.17 on 2026-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='validity_mode',
            field=models.CharField(choices=[('end_of_month', 'لحد آخر الشهر'), ('days', 'عدد أيام')], default='end_of_month', max_length=20, verbose_name='سريان العرض'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='quote_number_format',
            field=models.CharField(default='{code}-{year}/{month:02d}/{day:02d}', max_length=80, verbose_name='صيغة رقم العرض'),
        ),
    ]
